# Generated by Django 4.0.1 on 2022-01-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAFApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
    ]
