# Generated by Django 4.0.1 on 2022-01-25 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAFApp', '0002_rename_expenses_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='income',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='SAFApp.budget'),
        ),
    ]
